#! /bin/sh
chmod -x img/*.jpg img/weather/*.jpg *.pdf xepersian.dtx
xelatex -shell-escape xepersian.dtx
xelatex -shell-escape xepersian.dtx
xelatex -shell-escape xepersian.dtx
teckit_compile parsidigits.map
teckit_compile parsidigits.map
teckit_compile parsidigits.map
mkdir -p doc/xelatex/xepersian fonts/misc/xetex/fontmapping/xepersian source/xelatex/xepersian tex/xelatex/xepersian 
mkdir xepersian
mv *.def *.sty *.cls  tex/xelatex/xepersian
mv *.dtx *.ins source/xelatex/xepersian
mv *.pdf *.py *.tex README img doc/xelatex/xepersian
mv parsidigits.map parsidigits.tec fonts/misc/xetex/fontmapping/xepersian
zip -r xepersiantds doc/xelatex/xepersian fonts/misc/xetex/fontmapping/xepersian source/xelatex/xepersian tex/xelatex/xepersian
mv xepersiantds.zip xepersian.tds.zip
mv doc/xelatex/xepersian/*.pdf doc/xelatex/xepersian/*.py doc/xelatex/xepersian/README  doc/xelatex/xepersian/img source/xelatex/xepersian/*.dtx source/xelatex/xepersian/*.ins  xepersian
zip -r xepersian xepersian.tds.zip xepersian
rm -r doc tex source fonts xepersian
rm *.aux *.glo *.gls *.hd *.idx *.ilg *.ind *.log *.out *.toc xepersian.tds.zip



